SECTION_WRAPPER_ID = "section-wrapper-id"

VARIABLES_INFORMATION_ID = "variables-information"
ACCORDION_WRAPPER_ID = "accordion-wrapper"
ADD_USE_RESTRICTION_BUTTON = "add-use-restriction-button"
FORCE_RERENDER_COUNTER = "force-rerender-counter"
USE_RESTRICTION_STORE = "use-restriction-store"
USE_RESTRICTION_OPTION_STORE = "use-restriction-options-store"
USE_RESTRICTION_ID_STORE = "use-restriction-id-store"
USE_RESTRICTION_LIST_CONTAINER = "use-restriction-list-container"
GLOBAL_VARIABLES_ID = "global-variables"
ADD_GLOBAL_VARIABLES_BUTTON = "add-global-variables-button"
GLOBAL_ALERTS = "global-alerts"
FORCE_RERENDER_GLOBALS_COUNTER = "force-rerender-globals-counter"
GLOBAL_VARIABLES_STORE = "global-variables-store"
GLOBAL_OUTPUT = "global-output"
