SECTION_WRAPPER_ID = "section-wrapper-id"

VARIABLES_INFORMATION_ID = "variables-information"
ACCORDION_WRAPPER_ID = "accordion-wrapper"
ADD_USE_RESTRICTION_BUTTON = "add-use-restriction-button"
FORCE_RERENDER_COUNTER = "force-rerender-counter"
USE_RESTRICTION_STORE = "use-restriction-store"
USE_RESTRICTION_OPTION_STORE = "use-restriction-options-store"
USE_RESTRICTION_ID_STORE = "use-restriction-id-store"
USE_RESTRICTION_LIST_CONTAINER = "use-restriction-list-container"

GLOBAL_VARIABLES_ACCORDION = "global-variables-accordion"
GLOBAL_INFO_ALERTS_OUTPUT = "global-info-alerts-output"
GLOBAL_EDIT_SECTION = "global-edit-section"
ADD_GLOBAL_VARIABLES_BUTTON = "add-global-variables-button"
RESET_GLOBAL_VARIABLES_BUTTON = "reset-global-variables-button"
GLOBAL_EDITABLE = "global-editable"
GLOBAL_VARIABLES_ID = "global-variables"
GLOBAL_VARIABLES_STORE = "global-variables-store"
GLOBAL_VARIABLES_VALUES_STORE = "global-variables-values-store"
GLOBAL_ALERTS = "global-alerts"
GLOBAL_VARIABLES_INPUT = "global-variables-input"
