name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check-version.outputs.tag }}
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: true

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@b1778166f13188a9d478e2d1198f993011ba9864 # v2.0.3
        with:
          version-command: |
            bash -o pipefail -c "uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version"

      - name: Bump version for developmental release
        if: (!steps.check-version.outputs.tag)
        run: |
          version=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version) &&
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $version.dev.$(date +%s)

      - name: Build package
        run: |
          uv build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2

      - name: Publish package on TestPyPI
        if: (!steps.check-version.outputs.tag)
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}

  build-release-image:
    name: Build Release Image
    needs: release
    if: needs.release.outputs.tag != ''
    uses: ./.github/workflows/docker-build.yml
    with:
      tag: ${{ needs.release.outputs.tag }}
    permissions:
      contents: "read"
      id-token: "write"
    secrets: inherit
